### ISSUE TITLE
Proje yok

### ISSUE THREAD

**Issue by AdnanCigtekin** [BerkayKOCAK/e-commerce-crawler#1]
Hocam proje yok.

**Comment by BerkayKOCAK** [comment]
büyük sıkıntılarla karşılaştım adnancım, proje onlar çözülünce gelicek.

**Comment by BerkayKOCAK** [comment]
> Hocam proje yok.
büyük sıkıntılarla karşılaştım adnancım, proje onlar çözülünce gelecek.

**Comment by BerkayKOCAK** [comment]
> Hocam proje yok.


büyük sıkıntılarla karşılaştım adnancım, proje onlar çözülünce gelecek.

**Comment by AdnanCigtekin** [comment]
Analdım hocam
